/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisnisku.app;

/**
 *
 * @author Sanchie
 */
public class MainTycoonSandbox extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainTycoonSandbox.class.getName());

    /**
     * Creates new form MainTycoonSandbox
     */
    public MainTycoonSandbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jButtonDashboard = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonTransaksi = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonKategori = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonRekap = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonSimulasi = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonPeringkat = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        jButtonLogout = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                if (isOpaque()) {
                    g2.setColor(getBackground());
                    g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                }
                g2.dispose();

                boolean originalOpaque = isOpaque();
                setOpaque(false);
                super.paintComponent(g);
                setOpaque(originalOpaque);
            }
        };
        mainContentPanel = new javax.swing.JPanel();
        menuDashboard = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel21 = new javax.swing.JPanel();
        levelPanel = new javax.swing.JPanel();
        jP1level = new javax.swing.JLabel();
        jP1levelDesc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jP1namaBisnis = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jP1table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jP1modalAwal = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jP1totalKeluar = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jP1transaksiTerakhir = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jP1totalPemasukan = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jP1saldoSaatIni = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuTransaksi = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        menuKategori = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        menuRekap = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        menuSimulasi = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        menuPeringkat = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 233, 232)));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(140, 0));

        jTitle.setFont(new java.awt.Font("Poppins Medium", 1, 20)); // NOI18N
        jTitle.setForeground(new java.awt.Color(53, 100, 155));
        jTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisnisku/app/assets/logobinikuuu.png"))); // NOI18N
        jTitle.setText("Bisnisku");

        jButtonDashboard.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonDashboard.setForeground(new java.awt.Color(53, 100, 155));
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setContentAreaFilled(false);
        jButtonDashboard.setFocusPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDashboard.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDashboardMouseExited(evt);
            }
        });
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);

        jButtonTransaksi.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonTransaksi.setForeground(new java.awt.Color(53, 100, 155));
        jButtonTransaksi.setText("Transaksi");
        jButtonTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonTransaksi.setBorderPainted(false);
        jButtonTransaksi.setContentAreaFilled(false);
        jButtonTransaksi.setFocusPainted(false);
        jButtonTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTransaksi.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTransaksiMouseExited(evt);
            }
        });
        jButtonTransaksi.addActionListener(this::jButtonTransaksiActionPerformed);

        jButtonKategori.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonKategori.setForeground(new java.awt.Color(53, 100, 155));
        jButtonKategori.setText("Kategori");
        jButtonKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonKategori.setBorderPainted(false);
        jButtonKategori.setContentAreaFilled(false);
        jButtonKategori.setFocusPainted(false);
        jButtonKategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonKategori.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonKategoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonKategoriMouseExited(evt);
            }
        });
        jButtonKategori.addActionListener(this::jButtonKategoriActionPerformed);

        jButtonRekap.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonRekap.setForeground(new java.awt.Color(53, 100, 155));
        jButtonRekap.setText("Rekap ");
        jButtonRekap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonRekap.setBorderPainted(false);
        jButtonRekap.setContentAreaFilled(false);
        jButtonRekap.setFocusPainted(false);
        jButtonRekap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRekap.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonRekap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRekapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRekapMouseExited(evt);
            }
        });
        jButtonRekap.addActionListener(this::jButtonRekapActionPerformed);

        jButtonSimulasi.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonSimulasi.setForeground(new java.awt.Color(53, 100, 155));
        jButtonSimulasi.setText("Simulasi");
        jButtonSimulasi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonSimulasi.setBorderPainted(false);
        jButtonSimulasi.setContentAreaFilled(false);
        jButtonSimulasi.setFocusPainted(false);
        jButtonSimulasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSimulasi.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonSimulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSimulasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimulasiMouseExited(evt);
            }
        });
        jButtonSimulasi.addActionListener(this::jButtonSimulasiActionPerformed);

        jButtonPeringkat.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonPeringkat.setForeground(new java.awt.Color(53, 100, 155));
        jButtonPeringkat.setText("Peringkat");
        jButtonPeringkat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jButtonPeringkat.setBorderPainted(false);
        jButtonPeringkat.setContentAreaFilled(false);
        jButtonPeringkat.setFocusPainted(false);
        jButtonPeringkat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPeringkat.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonPeringkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPeringkatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPeringkatMouseExited(evt);
            }
        });
        jButtonPeringkat.addActionListener(this::jButtonPeringkatActionPerformed);

        jButtonLogout.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(251, 44, 54));
        jButtonLogout.setText("Keluar");
        jButtonLogout.setBorder(null);
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRekap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSimulasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPeringkat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSimulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        mainContentPanel.setBackground(new java.awt.Color(248, 250, 252));
        mainContentPanel.setLayout(new java.awt.CardLayout());

        menuDashboard.setBackground(new java.awt.Color(230, 246, 244));
        menuDashboard.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(230, 246, 244));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel21.setBackground(new java.awt.Color(248, 250, 252));

        levelPanel.setBackground(new java.awt.Color(232, 240, 254));
        levelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 67, 64)));
        levelPanel.setForeground(new java.awt.Color(255, 244, 238));

        jP1level.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jP1level.setForeground(new java.awt.Color(30, 58, 138));
        jP1level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jP1level.setText("Level: Pengusaha sehat");
        jP1level.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jP1levelDesc.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jP1levelDesc.setForeground(new java.awt.Color(30, 58, 138));
        jP1levelDesc.setText("Saldo masih ada di atas 80% modal");

        javax.swing.GroupLayout levelPanelLayout = new javax.swing.GroupLayout(levelPanel);
        levelPanel.setLayout(levelPanelLayout);
        levelPanelLayout.setHorizontalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP1level)
                    .addComponent(jP1levelDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        levelPanelLayout.setVerticalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP1level)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP1levelDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 100, 155));
        jLabel1.setText("Kesehatan Keuangan");

        jP1namaBisnis.setBackground(new java.awt.Color(204, 204, 204));
        jP1namaBisnis.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jP1namaBisnis.setForeground(new java.awt.Color(53, 100, 155));
        jP1namaBisnis.setText("Nama Bisnis");

        jProgressBar1.setBackground(new java.awt.Color(37, 37, 35));
        jProgressBar1.setForeground(new java.awt.Color(29, 157, 117));

        jP1table.setBackground(new java.awt.Color(51, 51, 51));
        jP1table.setForeground(new java.awt.Color(255, 255, 255));
        jP1table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Nominal", "Tanggal"
            }
        ));
        jP1table.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(jP1table);

        jPanel7.setBackground(new java.awt.Color(48, 48, 46));

        jPanel10.setBackground(new java.awt.Color(38, 38, 37));

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(221, 255, 255));
        jLabel19.setText("Modal Awal");

        jP1modalAwal.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jP1modalAwal.setForeground(new java.awt.Color(221, 255, 255));
        jP1modalAwal.setText("RP. 10jt");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jP1modalAwal))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jP1modalAwal)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(38, 38, 37));

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(221, 255, 255));
        jLabel20.setText("Total Keluar");

        jP1totalKeluar.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jP1totalKeluar.setForeground(new java.awt.Color(255, 123, 103));
        jP1totalKeluar.setText("RP. 10jt");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jP1totalKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jP1totalKeluar)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(38, 38, 37));

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(221, 255, 255));
        jLabel22.setText("Transaksi Terakhir");

        jP1transaksiTerakhir.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jP1transaksiTerakhir.setForeground(new java.awt.Color(221, 255, 255));
        jP1transaksiTerakhir.setText("RP. 10jt");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jP1transaksiTerakhir))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jP1transaksiTerakhir)
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(38, 38, 37));

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(221, 255, 255));
        jLabel23.setText("Total Pemasukan");

        jP1totalPemasukan.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jP1totalPemasukan.setForeground(new java.awt.Color(30, 158, 117));
        jP1totalPemasukan.setText("RP. 10jt");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jP1totalPemasukan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jP1totalPemasukan)
                .addContainerGap())
        );

        jPanel29.setBackground(new java.awt.Color(38, 38, 37));

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(221, 255, 255));
        jLabel25.setText("Saldo Saat ini");

        jP1saldoSaatIni.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jP1saldoSaatIni.setForeground(new java.awt.Color(30, 158, 117));
        jP1saldoSaatIni.setText("RP. 10jt");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jP1saldoSaatIni))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jP1saldoSaatIni)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 100, 155));
        jLabel5.setText("Ringkasan bisnis");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jP1namaBisnis))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jP1namaBisnis)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addComponent(levelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel21);

        menuDashboard.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuDashboard, "card2");

        menuTransaksi.setBackground(new java.awt.Color(230, 246, 244));
        menuTransaksi.setLayout(new java.awt.BorderLayout());

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        menuTransaksi.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuTransaksi, "card3");

        menuKategori.setBackground(new java.awt.Color(230, 246, 244));
        menuKategori.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(jScrollPane4);

        menuKategori.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuKategori, "card4");

        menuRekap.setBackground(new java.awt.Color(230, 246, 244));
        menuRekap.setLayout(new java.awt.BorderLayout());

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        menuRekap.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuRekap, "card5");

        menuSimulasi.setBackground(new java.awt.Color(230, 246, 244));
        menuSimulasi.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        menuSimulasi.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuSimulasi, "card6");

        menuPeringkat.setBackground(new java.awt.Color(230, 246, 244));
        menuPeringkat.setLayout(new java.awt.BorderLayout());

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        menuPeringkat.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(menuPeringkat, "card7");

        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        // TODO add your handling code here:
        mainContentPanel.removeAll();
        mainContentPanel.add(menuDashboard); 
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton(); 
        
        jButtonDashboard.setForeground(java.awt.Color.decode("#35649b"));
        jButtonDashboard.setOpaque(true);
        jButtonDashboard.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransaksiActionPerformed
        mainContentPanel.removeAll();
        mainContentPanel.add(menuTransaksi);
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton();
        
        jButtonTransaksi.setForeground(java.awt.Color.decode("#35649b"));
        jButtonTransaksi.setOpaque(true);
        jButtonTransaksi.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonTransaksiActionPerformed

    private void jButtonDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDashboardMouseEntered
        // TODO add your handling code here:
        jButtonDashboard.setOpaque(true);
        jButtonDashboard.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonDashboardMouseEntered

    private void jButtonDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDashboardMouseExited
        // TODO add your handling code here:
        if (!jButtonDashboard.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonDashboard.setOpaque(false); 
            jButtonDashboard.setBackground(null);
        }
    }//GEN-LAST:event_jButtonDashboardMouseExited

    private void jButtonTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTransaksiMouseEntered
        // TODO add your handling code here:
        jButtonTransaksi.setOpaque(true);
        jButtonTransaksi.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonTransaksiMouseEntered

    private void jButtonTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTransaksiMouseExited
        // TODO add your handling code here:
       if (!jButtonTransaksi.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonTransaksi.setOpaque(false); 
            jButtonTransaksi.setBackground(null);
        }
    }//GEN-LAST:event_jButtonTransaksiMouseExited

    private void jButtonKategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKategoriMouseEntered
        // TODO add your handling code here:
        jButtonKategori.setOpaque(true);
        jButtonKategori.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonKategoriMouseEntered

    private void jButtonKategoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKategoriMouseExited
        // TODO add your handling code here:
        if (!jButtonKategori.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonKategori.setOpaque(false); 
            jButtonKategori.setBackground(null);
        }
    }//GEN-LAST:event_jButtonKategoriMouseExited

    private void jButtonKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKategoriActionPerformed
        // TODO add your handling code here:
        mainContentPanel.removeAll();
        mainContentPanel.add(menuKategori); 
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton();
        
        jButtonKategori.setForeground(java.awt.Color.decode("#35649b"));
        jButtonKategori.setOpaque(true);
        jButtonKategori.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonKategoriActionPerformed

    private void jButtonRekapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRekapMouseEntered
        // TODO add your handling code here:
        jButtonRekap.setOpaque(true);
        jButtonRekap.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonRekapMouseEntered

    private void jButtonRekapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRekapMouseExited
        // TODO add your handling code here:
        if (!jButtonRekap.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonRekap.setOpaque(false); 
            jButtonRekap.setBackground(null);
        }
    }//GEN-LAST:event_jButtonRekapMouseExited

    private void jButtonRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRekapActionPerformed
        // TODO add your handling code here:
        mainContentPanel.removeAll();
        mainContentPanel.add(menuRekap); 
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton();
        
        jButtonRekap.setForeground(java.awt.Color.decode("#35649b"));
        jButtonRekap.setOpaque(true);
        jButtonRekap.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonRekapActionPerformed

    private void jButtonSimulasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimulasiMouseEntered
        // TODO add your handling code here:
        jButtonSimulasi.setOpaque(true);
        jButtonSimulasi.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonSimulasiMouseEntered

    private void jButtonSimulasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimulasiMouseExited
        // TODO add your handling code here:
        if (!jButtonSimulasi.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonSimulasi.setOpaque(false); 
            jButtonSimulasi.setBackground(null);
        }
    }//GEN-LAST:event_jButtonSimulasiMouseExited

    private void jButtonSimulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimulasiActionPerformed
        // TODO add your handling code here:
        mainContentPanel.removeAll();
        mainContentPanel.add(menuSimulasi); 
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton();
        
        jButtonSimulasi.setForeground(java.awt.Color.decode("#35649b"));
        jButtonSimulasi.setOpaque(true);
        jButtonSimulasi.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonSimulasiActionPerformed

    private void jButtonPeringkatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPeringkatMouseEntered
        // TODO add your handling code here:
        jButtonPeringkat.setOpaque(true);
        jButtonPeringkat.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonPeringkatMouseEntered

    private void jButtonPeringkatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPeringkatMouseExited
        // TODO add your handling code here:
        if (!jButtonPeringkat.getForeground().equals(java.awt.Color.decode("#35649b"))) {
            jButtonPeringkat.setOpaque(false); 
            jButtonPeringkat.setBackground(null);
        }
    }//GEN-LAST:event_jButtonPeringkatMouseExited

    private void jButtonPeringkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeringkatActionPerformed
        // TODO add your handling code here:
        mainContentPanel.removeAll();
        mainContentPanel.add(menuPeringkat); 
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        
        resetSemuaButton();
        
        jButtonPeringkat.setForeground(java.awt.Color.decode("#35649b"));
        jButtonPeringkat.setOpaque(true);
        jButtonPeringkat.setBackground(java.awt.Color.decode("#E8F0FE"));
    }//GEN-LAST:event_jButtonPeringkatActionPerformed

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        // TODO add your handling code here:
        jButtonLogout.setOpaque(true);
        jButtonLogout.setBackground(java.awt.Color.decode("#FEE2E2"));
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        // TODO add your handling code here:
        jButtonLogout.setOpaque(false); 
        jButtonLogout.setBackground(null);
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void resetSemuaButton() {
        java.awt.Color warnaAbu = java.awt.Color.decode("#707071");
        
        jButtonDashboard.setForeground(warnaAbu);
        jButtonDashboard.setOpaque(false);
        jButtonDashboard.setBackground(null);
        
        jButtonTransaksi.setForeground(warnaAbu);
        jButtonTransaksi.setOpaque(false);
        jButtonTransaksi.setBackground(null);
        
        jButtonKategori.setForeground(warnaAbu);
        jButtonKategori.setOpaque(false);
        jButtonKategori.setBackground(null);
        
        jButtonRekap.setForeground(warnaAbu);
        jButtonRekap.setOpaque(false);
        jButtonRekap.setBackground(null);
        
        jButtonSimulasi.setForeground(warnaAbu);
        jButtonSimulasi.setOpaque(false);
        jButtonSimulasi.setBackground(null);
        
        jButtonPeringkat.setForeground(warnaAbu);
        jButtonPeringkat.setOpaque(false);
        jButtonPeringkat.setBackground(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainTycoonSandbox().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonKategori;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPeringkat;
    private javax.swing.JButton jButtonRekap;
    private javax.swing.JButton jButtonSimulasi;
    private javax.swing.JButton jButtonTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jP1level;
    private javax.swing.JLabel jP1levelDesc;
    private javax.swing.JLabel jP1modalAwal;
    private javax.swing.JLabel jP1namaBisnis;
    private javax.swing.JLabel jP1saldoSaatIni;
    private javax.swing.JTable jP1table;
    private javax.swing.JLabel jP1totalKeluar;
    private javax.swing.JLabel jP1totalPemasukan;
    private javax.swing.JLabel jP1transaksiTerakhir;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel jTitle;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuKategori;
    private javax.swing.JPanel menuPeringkat;
    private javax.swing.JPanel menuRekap;
    private javax.swing.JPanel menuSimulasi;
    private javax.swing.JPanel menuTransaksi;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
