/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisnisku.app;

import java.sql.PreparedStatement;

/**
 *
 * @author Ihsan
 */
public class RegisterForm extends javax.swing.JFrame {

    connection conn;

    /**
     * Creates new form Register
     */
    public RegisterForm() {
        initComponents();
        conn = new connection();
        // Clear placeholder Username
        jTextFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextFieldUsername.getText().equals("Masukan Username")) {
                    jTextFieldUsername.setText("");
                    jTextFieldUsername.setForeground(new java.awt.Color(204, 204, 204));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextFieldUsername.getText().isEmpty()) {
                    jTextFieldUsername.setText("Masukan Username");
                    jTextFieldUsername.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });

        // Clear placeholder Password
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (new String(jPasswordField1.getPassword()).equals("jPasswordField1")) {
                    jPasswordField1.setText("");
                    jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (new String(jPasswordField1.getPassword()).isEmpty()) {
                    jPasswordField1.setText("jPasswordField1");
                    jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });

        // Clear placeholder Konfirmasi Password
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (new String(jPasswordField2.getPassword()).equals("jPasswordField1")) {
                    jPasswordField2.setText("");
                    jPasswordField2.setForeground(new java.awt.Color(204, 204, 204));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (new String(jPasswordField2.getPassword()).isEmpty()) {
                    jPasswordField2.setText("jPasswordField1");
                    jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jHeading1 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jsubHead = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelKPassword = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jLabelMasuk = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        redirectLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(69, 69, 67));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(39, 39, 37));
        jPanel1.setToolTipText("");
        jPanel1.setRequestFocusEnabled(false);

        jTitle.setFont(new java.awt.Font("Poppins Medium", 1, 20)); // NOI18N
        jTitle.setForeground(new java.awt.Color(255, 255, 255));
        jTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisnisku/app/assets/logobinikuuu.png"))); // NOI18N
        jTitle.setText("Bisnisku tycoon");

        jPanel2.setBackground(new java.awt.Color(49, 49, 47));

        jHeading1.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jHeading1.setForeground(new java.awt.Color(255, 255, 255));
        jHeading1.setText("Buat akun baru");

        jLabelUsername.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(164, 164, 161));
        jLabelUsername.setText("Username");

        jsubHead.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jsubHead.setForeground(new java.awt.Color(155, 155, 151));
        jsubHead.setText("Mari mulai petualangan baru");

        jTextFieldUsername.setBackground(new java.awt.Color(49, 49, 47));
        jTextFieldUsername.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsername.setText("Masukan Username");
        jTextFieldUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(164, 164, 161));
        jLabelPassword.setText("Password");

        jLabelKPassword.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabelKPassword.setForeground(new java.awt.Color(164, 164, 161));
        jLabelKPassword.setText("Konfirmasi Password");

        jButtonRegister.setBackground(new java.awt.Color(49, 49, 47));
        jButtonRegister.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(204, 204, 204));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelMasuk.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabelMasuk.setForeground(new java.awt.Color(155, 155, 151));
        jLabelMasuk.setText("Sudah punya akun?");

        jPasswordField1.setBackground(new java.awt.Color(49, 49, 47));
        jPasswordField1.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jPasswordField2.setBackground(new java.awt.Color(49, 49, 47));
        jPasswordField2.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        redirectLogin.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        redirectLogin.setForeground(new java.awt.Color(27, 146, 93));
        redirectLogin.setText("Masuk");
        redirectLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jHeading1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jsubHead))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsername)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelKPassword)
                            .addComponent(jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabelMasuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redirectLogin)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jHeading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsubHead)
                .addGap(17, 17, 17)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMasuk)
                    .addComponent(redirectLogin))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        String username = jTextFieldUsername.getText();
        String password = new String(jPasswordField1.getPassword());
        String konfirmasi = new String(jPasswordField2.getPassword());

        if (username.isEmpty() || username.equals("Masukan Username") ||
            password.isEmpty() || password.equals("jPasswordField1") ||
            konfirmasi.isEmpty() || konfirmasi.equals("jPasswordField1")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom harus diisi ya!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(konfirmasi)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak cocok!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO users (username, password) VALUES (?, ?)";

            PreparedStatement pst = conn.con.prepareStatement(sql);

            pst.setString(1, username);
            pst.setString(2, password);

            int barisTersimpan = pst.executeUpdate();

            if (barisTersimpan > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Yeay! Registrasi berhasil. Silakan login. 🎉");

                LoginForm loginWindow = new LoginForm();
                loginWindow.setVisible(true);

                this.dispose();

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data, silahkan coba lagi.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            jTextFieldUsername.setText("");
            jPasswordField1.setText("");
            jPasswordField2.setText("");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Yah, registrasi gagal: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void redirectLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirectLoginMouseClicked
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_redirectLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jHeading1;
    private javax.swing.JLabel jLabelKPassword;
    private javax.swing.JLabel jLabelMasuk;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel jsubHead;
    private javax.swing.JLabel redirectLogin;
    // End of variables declaration//GEN-END:variables
}
