/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bisnisku.app;

/**
 *
 * @author Mahesa
 */
public class SetUpBisnisProfilePanel extends javax.swing.JFrame {

    connection conn;

    /**
     * Creates new form SetUpBisnisProfilePanel
     */
    public SetUpBisnisProfilePanel() {
        initComponents();
        this.setTitle("Bisnisku App - Setup Bisnis");

        try {
            java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/bisnisku/app/assets/logobinikuuu.png"));
            this.setIconImage(icon);
        } catch (Exception e) {
            System.out.println("Gambar icon gagal dimuat: " + e.getMessage());
        }

        // modal konfirmasi ketika keluar dari app         
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(
                        SetUpBisnisProfilePanel.this,
                        "Apakah Anda yakin ingin keluar dari aplikasi?",
                        "Konfirmasi Keluar",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

        conn = new connection();
        
        bisnisName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (bisnisName.getText().startsWith("Contoh:")) {
                    bisnisName.setText("");
                    bisnisName.setForeground(new java.awt.Color(53, 100, 155));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (bisnisName.getText().isEmpty()) {
                    bisnisName.setText("Contoh: Warung Kopi Tskuy");
                    bisnisName.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });

        bisnisOwner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (bisnisOwner.getText().startsWith("Contoh:")) {
                    bisnisOwner.setText("");
                    bisnisOwner.setForeground(new java.awt.Color(53, 100, 155));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (bisnisOwner.getText().isEmpty()) {
                    bisnisOwner.setText("Contoh: Ahmad Supendi");
                    bisnisOwner.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });

        bisnisBudget.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (bisnisBudget.getText().startsWith("Contoh:")) {
                    bisnisBudget.setText("");
                    bisnisBudget.setForeground(new java.awt.Color(53, 100, 155));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (bisnisBudget.getText().isEmpty()) {
                    bisnisBudget.setText("Contoh: 8000000");
                    bisnisBudget.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bisnisName = new javax.swing.JTextField();
        bisnisOwner = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitCreateBisnis = new javax.swing.JButton();
        bisnisBudget = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(53, 100, 155));
        jTextField1.setText("Langkah ini hanya muncul sekali. Modal awal menjadi patokan semua kalkulasi.");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 100, 155), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 100, 155));
        jLabel2.setText("Nama Bisnis");

        bisnisName.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        bisnisName.setForeground(new java.awt.Color(53, 100, 155));
        bisnisName.setText("Contoh: Warung Kopi Tskuy");

        bisnisOwner.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        bisnisOwner.setForeground(new java.awt.Color(53, 100, 155));
        bisnisOwner.setText("Contoh: Ahmad Supendi");
        bisnisOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisnisOwnerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 100, 155));
        jLabel3.setText("Nama Pemilik");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 100, 155));
        jLabel5.setText("Jumlah uang yang kamu siapkan untuk bisnis ini");

        submitCreateBisnis.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        submitCreateBisnis.setForeground(new java.awt.Color(53, 100, 155));
        submitCreateBisnis.setText("Mulai Kelola Bisnis");
        submitCreateBisnis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 100, 155), 1, true));
        submitCreateBisnis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitCreateBisnisMouseClicked(evt);
            }
        });

        bisnisBudget.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        bisnisBudget.setForeground(new java.awt.Color(53, 100, 155));
        bisnisBudget.setText("Contoh: 8000000");
        bisnisBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisnisBudgetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 100, 155));
        jLabel6.setText("Modal Awal(Rp)");

        jPanel1.setBackground(new java.awt.Color(232, 240, 254));

        jLabel1.setBackground(new java.awt.Color(232, 240, 254));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 100, 155));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bisnisku/app/assets/logobinikuuu.png"))); // NOI18N
        jLabel1.setText("Setup Profile Bisnis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(bisnisName)
                    .addComponent(bisnisOwner)
                    .addComponent(jLabel3)
                    .addComponent(submitCreateBisnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bisnisBudget)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bisnisName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bisnisOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bisnisBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitCreateBisnis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bisnisOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisOwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisOwnerActionPerformed

    private void bisnisBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisBudgetActionPerformed

    private void submitCreateBisnisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitCreateBisnisMouseClicked
        // TODO add your handling code here:
        String namaBisnis = bisnisName.getText().trim();
        String namaPemilik = bisnisOwner.getText().trim();
        String budgetRaw = bisnisBudget.getText().trim();

        if (namaBisnis.isEmpty() || namaBisnis.startsWith("Contoh:")
                || namaPemilik.isEmpty() || namaPemilik.startsWith("Contoh:")
                || budgetRaw.isEmpty() || budgetRaw.startsWith("Contoh:")) {

            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom harus diisi dengan benar!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double modalAwal = 0;
        try {
            modalAwal = Double.parseDouble(budgetRaw);
            if (modalAwal < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Modal awal harus berupa angka positif!", "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int userId = UserSession.getUserId();
        if (userId <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sesi user tidak ditemukan. Silakan login kembali.", "Error Sesi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "INSERT INTO bisnis_profile (user_id, nama_bisnis, nama_pemilik, modal_awal) VALUES (?, ?, ?, ?)";

        try (java.sql.PreparedStatement ps = conn.con.prepareStatement(sql)) {

            ps.setInt(1, userId);
            ps.setString(2, namaBisnis);
            ps.setString(3, namaPemilik);
            ps.setDouble(4, modalAwal);

            int barisTerdampak = ps.executeUpdate();

            if (barisTerdampak > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Profile bisnis berhasil disimpan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                UserSession.setUserId(userId);
                UserSession.setNamaPemilik(namaPemilik);
                UserSession.setNamaBisnis(namaBisnis);
                UserSession.setModal(modalAwal);

                MainTycoonSandbox indexPage = new MainTycoonSandbox();
                indexPage.setVisible(true);

                this.dispose();
            }

        } catch (java.sql.SQLException e) {
            if (e.getErrorCode() == 1062) {
                javax.swing.JOptionPane.showMessageDialog(this, "Akun Anda sudah memiliki profil bisnis terdaftar!", "Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitCreateBisnisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUpBisnisProfilePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUpBisnisProfilePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUpBisnisProfilePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUpBisnisProfilePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUpBisnisProfilePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bisnisBudget;
    private javax.swing.JTextField bisnisName;
    private javax.swing.JTextField bisnisOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submitCreateBisnis;
    // End of variables declaration//GEN-END:variables
}
